DO
$$
BEGIN
   IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'agent') THEN
      CREATE ROLE agent LOGIN PASSWORD 'agent_pass';
   END IF;
END
$$;
GRANT CONNECT ON DATABASE business TO agent;
\c business
GRANT USAGE ON SCHEMA public TO agent;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO agent;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE ON TABLES TO agent;
